[workspace]

members = [
    "esi",
    "examples/esi_example_minimal",
    "examples/esi_example_advanced_error_handling",
    "examples/esi_try_example",
]

[workspace.package]
version = "0.4.2"
authors = ["Kailan Blanks <kblanks@fastly.com>"]
license = "MIT"
edition = "2018"
