# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["kblanks@fastly.com"]
description = ""
language = "rust"
manifest_version = 2
name = "esi_example_advanced_error_handling"
service_id = ""

[local_server]

  [local_server.backends]

    [local_server.backends.mock-s3]
      url = "https://mock-s3.edgecompute.app"

[scripts]
  build = "cargo build --bin esi_example_advanced_error_handling --release --target wasm32-wasi --color always"

[setup]

  [setup.backends]

    [setup.backends.mock-s3]
      address = "mock-s3.edgecompute.app"
      port = 443
